### ISSUE TITLE
Reading metadata for small files can consume lots of memory

### ISSUE THREAD

**Issue by tdsmith** [ome/ome-files-cpp#22]
Using the simple zzuf fuzzer I tried feeding fuzzed images into the `info` tool shipped with ome-files-cpp and found that large ImageWidth and ImageLength parameters in the TIFF header will cause `info` to attempt to allocate very large amounts of memory, leading to OOM kills in my testing VM, even for very small input files. Anecdotally, the libtiff `tiffinfo` tool also allocates large amounts of memory when examining these files but I could successfully run `tiffinfo` against these where I couldn't run the `info` tool.

I noticed that someone else filed [a similar bug](http://bugzilla.maptools.org/show_bug.cgi?id=2524) against libtiff last year with no resolution yet. It's not obvious that this is a _bug_ but it could be a DoS vector if ome-files-cpp backs a web application that accepts user data.

Here is a set of examples. Each of these is derived from the `single-channel.ome.tif` from the [OME-TIFF sample data](https://www.openmicroscopy.org/site/support/ome-model/ome-tiff/data.html) and is about 70k; they can lead to memory allocations of 8GB+: 
[examples.zip](https://github.com/ome/ome-files-cpp/files/344831/examples.zip)

**Comment by rleigh-dundee** [comment]
Thanks for doing this, it's very useful to know!  I'll do some profiling and further investigation with your sample data.

Since we are using libtiff almost directly, via a thin C++ RAII wrapper, it's certainly quite possible this is in libtiff.   At least for the `info` command, we don't read in any pixel data, so this is likely related to metadata and the number of strips/tiles.  I thought these were limited to a simple list of offsets in the metadata, but it's certainly possible they use more memory if there's something pathological going on.  The extra overhead of the ome-xml/ome-files metadata might explain why it's getting pushed past the limit, though this metadata doesn't store anything other than x/y size so should not exhibit scaling problems here.


Thanks again,
Roger

**Comment by rleigh-dundee** [comment]
@tdsmith I've done some profiling and testing.  I'll add more information here as I run through each file.

For `crash-231866`:
  Two allocations of 536871808*8 corresponds to the image image length / tilesize which is 536871079 / 2 +1 for the strip offset and byte count arrays.
  This is in `TIFFFetchStripThing()`; `tif_dirread.c` line 5399, called from `TIFFReadDirectory()`

It seems to intentionally handle the "broken" case where the number of entries is less than the `nstrips` count.  While this might make sense as a last-ditch attempt to read corrupt or badly-written TIFFs, it means that the IFD is inconsistent, so I'd rather see a hard failure here than to silently cope and continue.

**Comment by rleigh-codelibre** [comment]
Link added to here in the upstream bugzilla ticket.

**Comment by tdsmith** [comment]
Thanks for looking at these and following up with libtiff!
